http, fix some arg problems in mkcbundle

diff --git a/cbundle b/cbundle
--- a/cbundle
+++ b/cbundle
@@ -553,6 +553,19 @@ function main_install() {
     # $1 - file name
     local file_name=$1
 
+    # if it is a http url, pull the file using wget
+    if [[ ${file_name} == "http://*" ]] || [[ ${file_name} == "ftp://*" ]]; then
+        # pull the file down
+        local outfile=${TEMPDIR}/$(basename "${file_name}")
+        wget "${file_name}" -q -o "${outfile}"
+        file_name=${outfile}
+
+        if [ ! -f "${file_name}" ]; then
+            echo "Could not download file"
+            exit 1
+        fi
+    fi
+
     bundle_name=$(bundle_from_file "$file_name")
     bundle_version=$(version_from_file "$file_name")
 
